## ex2 -a) Numpy

In [1]:
# import numpy:

import numpy as np

In [2]:
# ndarray object:

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# ndim and shape:

a = np.array([[[1,2],[3,4]],[[2,1],[4,5]]])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2]
  [3 4]]

 [[2 1]
  [4 5]]]
3
(2, 2, 2)


In [4]:
# array indexing:

print(arr[0])
print(arr[0]+arr[2])
print(a[0,1,1])
print(a[-1][-1][-1])

1
4
4
5


In [5]:
# array slicing:

print(a[1:4])
print(a[0, 0:1])

[[[2 1]
  [4 5]]]
[[1 2]]


In [6]:
# data types:

b = np.array([1,2,3,4],dtype='i4')
print(b)
print(b.dtype)

[1 2 3 4]
int32


In [7]:
# type conversion:

arr = b.astype(float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [8]:
# copy and view:

x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1. 2. 3. 4.]


In [9]:
# reshaping ndarray:

print(a)
arr = a.reshape(4,2)
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[2 1]
  [4 5]]]
[[1 2]
 [3 4]
 [2 1]
 [4 5]]
(4, 2)


In [10]:
# itterate ndarray:

for x in np.nditer(a):
    print(x,end=' ')

1 2 3 4 2 1 4 5 

In [11]:
# enumerate ndarray

for idx, x in np.ndenumerate(a):
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 2
(1, 0, 1) 1
(1, 1, 0) 4
(1, 1, 1) 5


## ex2- b) Pandas

In [12]:
# import pandas:

import pandas as pd

In [13]:
# pandas series:

a = pd.Series([1,7,2])
print(a)

0    1
1    7
2    2
dtype: int64


In [14]:
# set custom index:

a.index = ['x', 'y','z']
print(a.iloc[0])
print(a['x'])

1
1


In [15]:
# pandas dataframe:

data1 = {
    "Name": ["Alex","Allson"],
    "Age": [18,19],
}
df1 = pd.DataFrame(data1)
print(df1)

     Name  Age
0    Alex   18
1  Allson   19


In [23]:
# locate:

print(df1.iloc[0])
print(df1.iloc[1,0])

Name    Alex
Age       18
Name: s1, dtype: object
Allson


In [17]:
# set custom index:

df1.index = ['s1','s2']
print(df1)

      Name  Age
s1    Alex   18
s2  Allson   19


In [18]:
# read from csv or json file:

df = pd.read_csv('./dataset/temp.csv')
print(df)
df = pd.read_json('./dataset/temp.json')
print(df)

     Name  Age
0    Alex   18
1  Allson   19
     Name  Age
0    Alex   18
1  Allson   19


In [19]:
# describe data:

print(df1.describe())

             Age
count   2.000000
mean   18.500000
std     0.707107
min    18.000000
25%    18.250000
50%    18.500000
75%    18.750000
max    19.000000


In [20]:
# adding new data:

df1.loc[len(df1)] = ["Guru", 18]
print(df1)

      Name  Age
s1    Alex   18
s2  Allson   19
2     Guru   18


In [21]:
# insert column:

df1.insert(2,"Number",a.tolist())
print(df1)

      Name  Age  Number
s1    Alex   18       1
s2  Allson   19       7
2     Guru   18       2


In [22]:
# drop column:

df1 = df1.drop("Number",axis=1)
print(df1)

      Name  Age
s1    Alex   18
s2  Allson   19
2     Guru   18
