### 4: SVD for Dimensionality Reduction and Predict Missing Values

In [1]:
import numpy as np
from numpy.linalg import svd

In [3]:
user_item_matrix = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
])

In [4]:
mean_values = np.mean(user_item_matrix, axis=1, where=user_item_matrix > 0)
mean_values

array([3.        , 2.5       , 2.33333333, 2.5       , 3.33333333])

In [5]:
filled_matrix = np.where(user_item_matrix == 0, mean_values[:, None], user_item_matrix)
filled_matrix

array([[5.        , 3.        , 3.        , 1.        ],
       [4.        , 2.5       , 2.5       , 1.        ],
       [1.        , 1.        , 2.33333333, 5.        ],
       [1.        , 2.5       , 2.5       , 4.        ],
       [3.33333333, 1.        , 5.        , 4.        ]])

In [8]:
U, sigma, Vt = svd(filled_matrix, full_matrices=False)
sigma_diag = np.diag(sigma)
print(U, '\n\n', sigma,'\n\n', Vt, '\n\n', sigma_diag )

[[-0.47166674 -0.58024539  0.16459262 -0.17449958]
 [-0.39309835 -0.43945778  0.16147424 -0.10623152]
 [-0.38714828  0.56626474  0.12730154 -0.71641801]
 [-0.39386745  0.35398301  0.59912132  0.59909475]
 [-0.56390496  0.15566766 -0.75609741  0.2934203 ]] 

 [12.51754739  5.17031988  2.12655091  0.78239144] 

 [[-0.52657488 -0.34619146 -0.56762602 -0.52978399]
 [-0.62276961 -0.23837803  0.0280833   0.74467796]
 [-0.15284928  0.83067416 -0.51171283  0.15737698]
 [-0.5581344   0.36511344  0.64433067 -0.37418732]] 

 [[12.51754739  0.          0.          0.        ]
 [ 0.          5.17031988  0.          0.        ]
 [ 0.          0.          2.12655091  0.        ]
 [ 0.          0.          0.          0.78239144]]
